/*
@license

dhtmlxGantt v.4.2.1 Professional Evaluation
This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
!function(){function t(t){function e(e){var i={gantt:t.$keyboardNavigation.GanttNode,headerCell:t.$keyboardNavigation.HeaderCell,taskRow:t.$keyboardNavigation.TaskRow,taskCell:t.$keyboardNavigation.HeaderCell};return i[e]||i.gantt}t.config.keyboard_navigation=!0,t.config.keyboard_navigation_cells=!1,t.addShortcut=function(t,i,n){var a=e(n);a&&a.prototype.bind(t,i)},t.getShortcutHandler=function(i,n){var a=e(n);if(a){var r=t.$keyboardNavigation.shortcuts.parse(i);if(r.length)return a.prototype.findHandler(r[0]);
}},t.removeShortcut=function(t,i){var n=e(i);n&&n.prototype.unbind(t)},t.focus=function(){var e=t.$keyboardNavigation.dispatcher;e.enable(),e.getActiveNode()?e.focusNode(e.getActiveNode()):e.setDefaultNode()},t.$keyboardNavigation={},t._compose=function(){for(var t=Array.prototype.slice.call(arguments,0),e={},i=0;i<t.length;i++){var n=t[i];"function"==typeof n&&(n=new n);for(var a in n)e[a]=n[a]}return e},t.$keyboardNavigation.shortcuts={createCommand:function(){return{modifiers:{shift:!1,alt:!1,
ctrl:!1,meta:!1},keyCode:null}},parse:function(t){for(var e=[],i=this.getExpressions(this.trim(t)),n=0;n<i.length;n++){for(var a=this.getWords(i[n]),r=this.createCommand(),s=0;s<a.length;s++)this.commandKeys[a[s]]?r.modifiers[a[s]]=!0:this.specialKeys[a[s]]?r.keyCode=this.specialKeys[a[s]]:r.keyCode=a[s].charCodeAt(0);e.push(r)}return e},getCommandFromEvent:function(t){var e=this.createCommand();e.modifiers.shift=!!t.shiftKey,e.modifiers.alt=!!t.altKey,e.modifiers.ctrl=!!t.ctrlKey,e.modifiers.meta=!!t.metaKey,
e.keyCode=t.which||t.keyCode;var i=String.fromCharCode(e.keyCode);return i&&(e.keyCode=i.toLowerCase().charCodeAt(0)),e},getHashFromEvent:function(t){return this.getHash(this.getCommandFromEvent(t))},getHash:function(t){var e=[];for(var i in t.modifiers)t.modifiers[i]&&e.push(i);return e.push(t.keyCode),e.join(this.junctionChar)},getExpressions:function(t){return t.split(this.junctionChar)},getWords:function(t){return t.split(this.combinationChar)},trim:function(t){return t.replace(/\s/g,"")},junctionChar:",",
combinationChar:"+",commandKeys:{shift:16,alt:18,ctrl:17,meta:!0},specialKeys:{backspace:8,tab:9,enter:13,esc:27,space:32,up:38,down:40,left:37,right:39,home:36,end:35,pageup:33,pagedown:34,"delete":46,insert:45,plus:107,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123}},t.$keyboardNavigation.EventHandler={_handlers:null,findHandler:function(e){this._handlers||(this._handlers={});var i=t.$keyboardNavigation.shortcuts,n=i.getHash(e);return this._handlers[n]},doAction:function(t,e){
var i=this.findHandler(t);i&&(i.call(this,e),e.preventDefault?e.preventDefault():e.returnValue=!1)},bind:function(e,i){this._handlers||(this._handlers={});for(var n=t.$keyboardNavigation.shortcuts,a=n.parse(e),r=0;r<a.length;r++)this._handlers[n.getHash(a[r])]=i},unbind:function(e){for(var i=t.$keyboardNavigation.shortcuts,n=i.parse(e),a=0;a<n.length;a++)this._handlers[i.getHash(n[a])]&&delete this._handlers[i.getHash(n[a])]},bindAll:function(t){for(var e in t)this.bind(e,t[e])},initKeys:function(){
this._handlers||(this._handlers={}),this.keys&&this.bindAll(this.keys)}},function(){t.$keyboardNavigation.getFocusableNodes=t._getFocusableNodes,t.$keyboardNavigation.trapFocus=function(e,i){if(9!=i.keyCode)return!1;for(var n=t.$keyboardNavigation.getFocusableNodes(e),a=document.activeElement,r=-1,s=0;s<n.length;s++)if(n[s]==a){r=s;break}if(i.shiftKey){if(0>=r){var o=n[n.length-1];if(o)return o.focus(),i.preventDefault(),!0}}else if(r>=n.length-1){var l=n[0];if(l)return l.focus(),i.preventDefault(),
!0}return!1}}(),t.$keyboardNavigation.GanttNode=function(){},t.$keyboardNavigation.GanttNode.prototype=t._compose(t.$keyboardNavigation.EventHandler,{focus:function(){t.focus()},blur:function(){},disable:function(){t.$container.setAttribute("tabindex","0")},enable:function(){t.$container&&t.$container.removeAttribute("tabindex")},isEnabled:function(){return t.$container.hasAttribute("tabindex")},scrollHorizontal:function(e){var i=t.dateFromPos(t.getScrollState().x),n=0>e?-t.config.step:t.config.step;
i=t.date.add(i,n,t.config.scale_unit),t.scrollTo(t.posFromDate(i))},scrollVertical:function(e){var i=t.getScrollState().y,n=t.config.row_height;t.scrollTo(null,i+(0>e?-1:1)*n)},keys:{"alt+left":function(t){this.scrollHorizontal(-1)},"alt+right":function(t){this.scrollHorizontal(1)},"alt+up":function(t){this.scrollVertical(-1)},"alt+down":function(t){this.scrollVertical(1)},"ctrl+z":function(){t.undo&&t.undo()},"ctrl+r":function(){t.redo&&t.redo()}}}),t.$keyboardNavigation.GanttNode.prototype.bindAll(t.$keyboardNavigation.GanttNode.prototype.keys),
t.$keyboardNavigation.KeyNavNode=function(){},t.$keyboardNavigation.KeyNavNode.prototype=t._compose(t.$keyboardNavigation.EventHandler,{isValid:function(){return!0},fallback:function(){return null},moveTo:function(e){t.$keyboardNavigation.dispatcher.setActiveNode(e)},compareTo:function(t){if(!t)return!1;for(var e in this){if(!!this[e]!=!!t[e])return!1;var i=!(!this[e]||!this[e].toString),n=!(!t[e]||!t[e].toString);if(n!=i)return!1;if(n&&i){if(t[e].toString()!=this[e].toString())return!1}else if(t[e]!=this[e])return!1;
}},getNode:function(){},focus:function(){var t=this.getNode();t&&(t.setAttribute("tabindex","-1"),t.focus&&t.focus())},blur:function(){var t=this.getNode();t&&t.setAttribute("tabindex","-1")}}),t.$keyboardNavigation.HeaderCell=function(t){this.index=t||0},t.$keyboardNavigation.HeaderCell.prototype=t._compose(t.$keyboardNavigation.KeyNavNode,{_handlers:null,isValid:function(){return!t.config.show_grid&&t.getVisibleTaskCount()?!1:!!t.getGridColumns()[this.index]||!t.getVisibleTaskCount()},fallback:function(){
if(!t.config.show_grid)return t.getVisibleTaskCount()?new t.$keyboardNavigation.TaskRow:null;for(var e=t.getGridColumns(),i=this.index;i>=0&&!e[i];)i--;return e[i]?new t.$keyboardNavigation.HeaderCell(i):null},getNode:function(){var e=t.$grid_scale.childNodes;return e[this.index]},keys:{left:function(){this.index>0&&this.moveTo(new t.$keyboardNavigation.HeaderCell(this.index-1))},right:function(){var e=t.getGridColumns();this.index<e.length-1&&this.moveTo(new t.$keyboardNavigation.HeaderCell(this.index+1));
},down:function(){var e,i=t.getChildren(t.config.root_id);i[0]&&(e=i[0]),e&&(t.config.keyboard_navigation_cells?this.moveTo(new t.$keyboardNavigation.TaskCell(e,this.index)):this.moveTo(new t.$keyboardNavigation.TaskRow(e)))},end:function(){var e=t.getGridColumns();this.moveTo(new t.$keyboardNavigation.HeaderCell(e.length-1))},home:function(){this.moveTo(new t.$keyboardNavigation.HeaderCell(0))},"enter, space":function(){var t=document.activeElement;t.click()},"ctrl+enter":function(){t.createTask({},this.taskId);
}}}),t.$keyboardNavigation.HeaderCell.prototype.bindAll(t.$keyboardNavigation.HeaderCell.prototype.keys),t.$keyboardNavigation.TaskRow=function(e){if(!e){var i=t.getChildren(t.config.root_id);i[0]&&(e=i[0])}this.taskId=e,t.isTaskExists(this.taskId)&&(this.index=t.getTaskIndex(this.taskId))},t.$keyboardNavigation.TaskRow.prototype=t._compose(t.$keyboardNavigation.KeyNavNode,{_handlers:null,isValid:function(){return t.isTaskExists(this.taskId)&&t.getTaskIndex(this.taskId)>-1},fallback:function(){if(!t.getVisibleTaskCount()){
var e=new t.$keyboardNavigation.HeaderCell;return e.isValid()?e:null}var i=t._order,n=-1;if(i[this.index-1])n=this.index-1;else if(i[this.index+1])n=this.index+1;else for(var a=this.index;a>=0;){if(void 0!==i[a]){n=a;break}a--}return n>-1?new t.$keyboardNavigation.TaskRow(i[n]):void 0},getNode:function(){return t.isTaskExists(this.taskId)&&t.isTaskVisible(this.taskId)?t.config.show_grid?t.$grid.querySelector(".gantt_row["+t.config.task_attribute+"='"+this.taskId+"']"):t.getTaskNode(this.taskId):void 0;
},focus:function(){t.showTask(this.taskId),t.$keyboardNavigation.KeyNavNode.prototype.focus.apply(this)},keys:{pagedown:function(){t._order.length&&this.moveTo(new t.$keyboardNavigation.TaskRow(t._order[t._order.length-1]))},pageup:function(){t._order.length&&this.moveTo(new t.$keyboardNavigation.TaskRow(t._order[0]))},up:function(){var e=null,i=t.getPrev(this.taskId);e=i?new t.$keyboardNavigation.TaskRow(i):new t.$keyboardNavigation.HeaderCell,this.moveTo(e)},down:function(){var e=t.getNext(this.taskId);
e&&this.moveTo(new t.$keyboardNavigation.TaskRow(e))},space:function(e){t.getState().selected_task!=this.taskId?t.selectTask(this.taskId):t.unselectTask(this.taskId)},"ctrl+left":function(e){t.close(this.taskId)},"ctrl+right":function(e){t.open(this.taskId)},"delete":function(e){t.$click.buttons["delete"](this.taskId)},enter:function(){t.showLightbox(this.taskId)},"ctrl+enter":function(){t.createTask({},this.taskId)}}}),t.$keyboardNavigation.TaskRow.prototype.bindAll(t.$keyboardNavigation.TaskRow.prototype.keys),
t.$keyboardNavigation.TaskCell=function(e,i){if(!e){var n=t.getChildren(t.config.root_id);n[0]&&(e=n[0])}this.taskId=e,this.columnIndex=i||0,this.index=t.getTaskIndex(this.taskId)},t.$keyboardNavigation.TaskCell.prototype=t._compose(t.$keyboardNavigation.TaskRow,{_handlers:null,isValid:function(){return t.$keyboardNavigation.TaskRow.prototype.isValid.call(this)&&!!t.getGridColumns()[this.columnIndex]},fallback:function(){var e=t.$keyboardNavigation.TaskRow.prototype.fallback.call(this);if(e instanceof t.$keyboardNavigation.TaskRow){
for(var i=t.getGridColumns(),n=this.columnIndex;n>=0&&!i[n];)n--;return i[n]?new t.$keyboardNavigation.TaskCell(e.taskId,n):e}},getNode:function(){if(t.isTaskExists(this.taskId)&&t.isTaskVisible(this.taskId)){if(t.config.show_grid){var e=t.$grid.querySelector(".gantt_row["+t.config.task_attribute+"='"+this.taskId+"']");return e.childNodes[this.columnIndex]}return t.getTaskNode(this.taskId)}},keys:{up:function(){var e=null,i=t.getPrev(this.taskId);e=i?new t.$keyboardNavigation.TaskCell(i,this.columnIndex):new t.$keyboardNavigation.HeaderCell(this.columnIndex),
this.moveTo(e)},down:function(){var e=t.getNext(this.taskId);e&&this.moveTo(new t.$keyboardNavigation.TaskCell(e,this.columnIndex))},left:function(){this.columnIndex>0&&this.moveTo(new t.$keyboardNavigation.TaskCell(this.taskId,this.columnIndex-1))},right:function(){var e=t.getGridColumns();this.columnIndex<e.length-1&&this.moveTo(new t.$keyboardNavigation.TaskCell(this.taskId,this.columnIndex+1))},end:function(){var e=t.getGridColumns();this.moveTo(new t.$keyboardNavigation.TaskCell(this.taskId,e.length-1));
},home:function(){this.moveTo(new t.$keyboardNavigation.TaskCell(this.taskId,0))},pagedown:function(){t._order.length&&this.moveTo(new t.$keyboardNavigation.TaskCell(t._order[t._order.length-1],this.columnIndex))},pageup:function(){t._order.length&&this.moveTo(new t.$keyboardNavigation.TaskCell(t._order[0],this.columnIndex))}}}),t.$keyboardNavigation.TaskCell.prototype.bindAll(t.$keyboardNavigation.TaskRow.prototype.keys),t.$keyboardNavigation.TaskCell.prototype.bindAll(t.$keyboardNavigation.TaskCell.prototype.keys),
function(){function e(){return!!_.length}function i(i){setTimeout(function(){e()||t.focus()},1)}function n(e){t.eventRemove(e,"keydown",s),t.event(e,"keydown",s),_.push(e)}function a(){var e=_.pop();e&&t.eventRemove(e,"keydown",s),i(e)}function r(t){return t==_[_.length-1]}function s(e){var e=e||window.event,i=e.currentTarget;r(i)&&t.$keyboardNavigation.trapFocus(i,e)}function o(){n(t.getLightbox())}function l(){c=document.activeElement}function d(){setTimeout(function(){c&&(c.focus(),c=null)},1);
}var _=[];t.attachEvent("onLightbox",o),t.attachEvent("onAfterLightbox",a),t.attachEvent("onLightboxChange",function(){a(),o()}),t.attachEvent("onAfterQuickInfo",function(){i()}),t.attachEvent("onMessagePopup",function(t){l(),n(t)}),t.attachEvent("onAfterMessagePopup",function(){a(),d()});var c=null;t.$keyboardNavigation.isModal=e}(),t.$keyboardNavigation.dispatcher={isActive:!1,activeNode:null,globalNode:new t.$keyboardNavigation.GanttNode,enable:function(){this.isActive=!0,this.globalNode.enable(),
this.setActiveNode(this.getActiveNode())},disable:function(){this.isActive=!1,this.globalNode.disable()},isEnabled:function(){return!!this.isActive},getDefaultNode:function(){var e;return e=t.config.keyboard_navigation_cells?new t.$keyboardNavigation.TaskCell:new t.$keyboardNavigation.TaskRow,e.isValid()||(e=e.fallback()),e},setDefaultNode:function(){this.setActiveNode(this.getDefaultNode())},getActiveNode:function(){var t=this.activeNode;return t&&!t.isValid()&&(t=t.fallback()),t},focusGlobalNode:function(){
this.blurNode(this.globalNode),this.focusNode(this.globalNode)},setActiveNode:function(t){this.activeNode&&this.activeNode.compareTo(t)||this.isEnabled()&&(this.blurNode(this.activeNode),this.activeNode=t,this.focusNode(this.activeNode))},focusNode:function(t){t&&t.focus&&t.focus()},blurNode:function(t){t&&t.blur&&t.blur()},keyDownHandler:function(e){if(!t.$keyboardNavigation.isModal()&&this.isEnabled()){e=e||window.event;var i=this.globalNode,n=t.$keyboardNavigation.shortcuts.getCommandFromEvent(e),a=this.getActiveNode();
a?a.findHandler(n)?a.doAction(n,e):i.findHandler(n)&&i.doAction(n,e):this.setDefaultNode()}}},function(){var e=t.$keyboardNavigation.dispatcher,i=function(i){return t.config.keyboard_navigation?e.keyDownHandler(i):void 0},n=function(){e.focusGlobalNode()};t.attachEvent("onDataRender",function(){if(t.config.keyboard_navigation&&e.isEnabled()){var i=e.getActiveNode();i&&i.focus()}}),t.attachEvent("onGanttRender",function(){t.eventRemove(document,"keydown",i),t.eventRemove(t.$container,"focus",n),t.config.keyboard_navigation?(t.event(document,"keydown",i),
t.event(t.$container,"focus",n),t.$container.setAttribute("tabindex","0")):t.$container.removeAttribute("tabindex")});var a=t.attachEvent("onGanttReady",function(){t.detachEvent(a);var i=t.refreshTask;if(t.refreshTask=function(n){var a=i.apply(this,arguments);if(t.config.keyboard_navigation&&e.isEnabled()){var r=e.getActiveNode();r&&r.taskId==n&&e.focusNode(r)}return a},t._smart_render){var n=t._smart_render._redrawItems;t._smart_render._redrawItems=function(i,a){var r=n.apply(this,arguments);if(t.config.keyboard_navigation&&e.isEnabled()){
var s=e.getActiveNode();if(s&&void 0!==s.taskId)for(var o=0;o<a.length;o++)if(a[o].id==s.taskId){e.focusNode(s);break}}return r}}});t.attachEvent("onAfterTaskAdd",function(i,n){return t.config.keyboard_navigation?void(e.isEnabled()&&e.setActiveNode(new t.$keyboardNavigation.TaskRow(i))):!0}),t.attachEvent("onTaskClick",function(i){return t.config.keyboard_navigation?(e.enable(),e.setActiveNode(new t.$keyboardNavigation.TaskRow(i)),!0):!0}),t.attachEvent("onEmptyClick",function(){return t.config.keyboard_navigation?void e.enable():!0;
}),setInterval(function(){if(t.config.keyboard_navigation){var i,n=document.activeElement,a=t.$container;if(!n||t._locate_css(n,"gantt_cal_quick_info"))i=!1;else{for(;n!=a&&n;)n=n.parentNode;i=n==a?!0:!1}i&&!e.isEnabled()?e.enable():!i&&e.isEnabled()&&e.disable()}},500)}()}window.Gantt?window.Gantt.plugin(t):t(window.gantt)}();
//# sourceMappingURL=../sources/ext/dhtmlxgantt_keyboard_navigation.js.map