/*
@license

dhtmlxGantt v.4.2.1 Professional Evaluation
This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t.config.undo_steps=10,t.config.undo=!0,t.config.redo=!0,t.undo=function(){this._undo.undo()},t.getUndoStack=function(){return this._undo._undoStack},t.getRedoStack=function(){return this._undo._redoStack},t.redo=function(){this._undo.redo()},t.config.undo_types={link:"link",task:"task"},t.config.undo_actions={update:"update",remove:"remove",add:"add"},t._undo={_undoStack:[],_redoStack:[],maxSteps:10,undo_enabled:!0,redo_enabled:!0,_push:function(t,e){if(e.commands.length){
for(t.push(e);t.length>this.maxSteps;)t.shift();return e}},_pop:function(t){return t.pop()},undo:function(){if(this.updateConfigs(),this.undo_enabled){var e=this._pop(this._undoStack);t.callEvent("onBeforeUndo",[e])!==!1&&e&&(this._applyAction(this.action.invert(e)),this._push(this._redoStack,e)),t.callEvent("onAfterUndo",[])}},redo:function(){if(this.updateConfigs(),this.redo_enabled){var e=this._pop(this._redoStack);t.callEvent("onBeforeRedo",[e])!==!1&&e&&(this._applyAction(e),this._push(this._undoStack,e)),
t.callEvent("onAfterRedo",[])}},_applyAction:function(e){var i=null,n=this.command.entity,a=this.command.type,r={};r[n.task]={add:"addTask",update:"updateTask",remove:"deleteTask",isExists:"isTaskExists"},r[n.link]={add:"addLink",update:"updateLink",remove:"deleteLink",isExists:"isLinkExists"},t.batchUpdate(function(){for(var n=0;n<e.commands.length;n++){i=e.commands[n];var s=r[i.entity][i.type],o=r[i.entity].isExists;i.type==a.add?t[s](i.oldValue,i.oldValue.parent,i.oldValue.$index):i.type==a.remove?t[o](i.value.id)&&t[s](i.value.id):i.type==a.update&&t[s](i.value.id,i.value);
}})},logAction:function(t){this._push(this._undoStack,t),this._redoStack=[]},action:{create:function(t){return{commands:t?t.slice():[]}},invert:function(e){for(var i=t.copy(e),n=t._undo.command,a=0;a<e.commands.length;a++){var r=i.commands[a]=n.invert(i.commands[a]);if(r.type==n.type.update){var s=r.value;r.value=r.oldValue,r.oldValue=s}}return i}},command:{create:function(e,i,n,a){return{entity:a,type:n,value:t.copy(e),oldValue:t.copy(i||e)}},invert:function(e){var i=t.copy(e);return i.type=this.inverseCommands(e.type),
i},entity:null,type:null,inverseCommands:function(e){switch(e){case this.type.update:return this.type.update;case this.type.remove:return this.type.add;case this.type.add:return this.type.remove;case this.type.load:return this.type.clear;case this.type.clear:return this.type.load;default:return t.assert(!1,"Invalid command "+e),null}}},monitor:{_batchAction:null,_batchMode:!1,_ignore:!1,startIgnore:function(){this._ignore=!0},stopIgnore:function(){this._ignore=!1},startBatchAction:function(){this.timeout&&clearTimeout(this.timeout),
this.timeout=setTimeout(function(){t._undo.monitor.stopBatchAction()},10),this._ignore||this._batchMode||(this._batchMode=!0,this._batchAction=t._undo.action.create())},stopBatchAction:function(){if(!this._ignore){var e=t._undo;this._batchAction&&e.logAction(this._batchAction),this._batchMode=!1,this._batchAction=null}},_storeCommand:function(e){var i=t._undo;if(i.updateConfigs(),i.undo_enabled)if(this._batchMode)this._batchAction.commands.push(e);else{var n=i.action.create([e]);i.logAction(n)}},
_storeEntityCommand:function(e,i,n,a){var r=t._undo,s=r.command.create(e,i,n,a);this._storeCommand(s)},_storeTaskCommand:function(e,i){this._storeEntityCommand(e,this.getInitialTask(e.id),i,t._undo.command.entity.task)},_storeLinkCommand:function(e,i){this._storeEntityCommand(e,this.getInitialLink(e.id),i,t._undo.command.entity.link)},onTaskAdded:function(e){this._ignore||this._storeTaskCommand(e,t._undo.command.type.add)},onTaskUpdated:function(e){this._ignore||this._storeTaskCommand(e,t._undo.command.type.update);
},onTaskDeleted:function(e){if(!this._ignore){if(this._storeTaskCommand(e,t._undo.command.type.remove),this._nestedTasks[e.id])for(var i=this._nestedTasks[e.id],n=0;n<i.length;n++)this._storeTaskCommand(i[n],t._undo.command.type.remove);if(this._nestedLinks[e.id])for(var a=this._nestedLinks[e.id],n=0;n<a.length;n++)this._storeLinkCommand(a[n],t._undo.command.type.remove)}},onLinkAdded:function(e){this._ignore||this._storeLinkCommand(e,t._undo.command.type.add)},onLinkUpdated:function(e){this._ignore||this._storeLinkCommand(e,t._undo.command.type.update);
},onLinkDeleted:function(e){this._ignore||this._storeLinkCommand(e,t._undo.command.type.remove)},_initialTasks:{},_nestedTasks:{},_nestedLinks:{},_getLinks:function(t){return t.$source.concat(t.$target)},setNestedTasks:function(e,i){for(var n=null,a=[],r=this._getLinks(t.getTask(e)),s=0;s<i.length;s++)n=this.setInitialTask(i[s]),r=r.concat(this._getLinks(n)),a.push(n);for(var o={},s=0;s<r.length;s++)o[r[s]]=!0;var l=[];for(var s in o)l.push(this.setInitialLink(s));this._nestedTasks[e]=a,this._nestedLinks[e]=l;
},setInitialTask:function(e){if(!this._initialTasks[e]||!this._batchMode){var i=t.copy(t.getTask(e));i.$index=t.getTaskIndex(e),this._initialTasks[e]=i}return this._initialTasks[e]},getInitialTask:function(t){return this._initialTasks[t]},_initialLinks:{},setInitialLink:function(e){return this._initialLinks[e]&&this._batchMode||(this._initialLinks[e]=t.copy(t.getLink(e))),this._initialLinks[e]},getInitialLink:function(t){return this._initialLinks[t]}}},t._undo.updateConfigs=function(){t._undo.maxSteps=t.config.undo_steps,
t._undo.command.entity=t.config.undo_types,t._undo.command.type=t.config.undo_actions,t._undo.undo_enabled=!!t.config.undo,t._undo.redo_enabled=!!t.config.undo&&!!t.config.redo},function(){function e(t){return l.setInitialTask(t),!0}function i(t,e,i){t&&(t.id==e&&(t.id=i),t.parent==e&&(t.parent=i))}function n(t,e,n){i(t.value,e,n),i(t.oldValue,e,n)}function a(t,e,i){t&&(t.source==e&&(t.source=i),t.target==e&&(t.target=i))}function r(t,e,i){a(t.value,e,i),a(t.oldValue,e,i)}function s(e,i,a){for(var s=t._undo,o=0;o<e.length;o++)for(var l=e[o],d=0;d<l.commands.length;d++)l.commands[d].entity==s.command.entity.task?n(l.commands[d],i,a):l.commands[d].entity==s.command.entity.link&&r(l.commands[d],i,a);
}function o(e,i,n){for(var a=t._undo,r=0;r<e.length;r++)for(var s=e[r],o=0;o<s.commands.length;o++){var l=s.commands[o];l.entity==a.command.entity.link&&(l.value&&l.value.id==i&&(l.value.id=n),l.oldValue&&l.oldValue.id==i&&(l.oldValue.id=n))}}var l=t._undo.monitor,d={onBeforeUndo:"onAfterUndo",onBeforeRedo:"onAfterRedo"};for(var _ in d)t.attachEvent(_,function(){l.startIgnore()}),t.attachEvent(d[_],function(){l.stopIgnore()});for(var c=["onTaskDragStart","onAfterTaskDelete","onBeforeBatchUpdate"],_=0;_<c.length;_++)t.attachEvent(c[_],function(){
l.startBatchAction()});t.attachEvent("onBeforeTaskDrag",e),t.attachEvent("onLightbox",e),t.attachEvent("onBeforeTaskAutoSchedule",function(t){return e(t.id),!0}),t.attachEvent("onBeforeTaskDelete",function(i){e(i);var n=[];return t.eachTask(function(t){n.push(t.id)},i),l.setNestedTasks(i,n),!0}),t.attachEvent("onAfterTaskAdd",function(t,e){l.onTaskAdded(e)}),t.attachEvent("onAfterTaskUpdate",function(t,e){l.onTaskUpdated(e)}),t.attachEvent("onAfterTaskDelete",function(t,e){l.onTaskDeleted(e)}),t.attachEvent("onAfterLinkAdd",function(t,e){
l.onLinkAdded(e)}),t.attachEvent("onAfterLinkUpdate",function(t,e){l.onLinkUpdated(e)}),t.attachEvent("onAfterLinkDelete",function(t,e){l.onLinkDeleted(e)}),t.attachEvent("onTaskIdChange",function(e,i){var n=t._undo;s(n._undoStack,e,i),s(n._redoStack,e,i)}),t.attachEvent("onLinkIdChange",function(e,i){var n=t._undo;o(n._undoStack,e,i),o(n._redoStack,e,i)}),t.attachEvent("onGanttReady",function(){t._undo.updateConfigs()})}()});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_undo.js.map