/*
@license

dhtmlxGantt v.4.2.1 Professional Evaluation
This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Gantt.plugin(function(t){t._formatLink=function(e){var n=[],a=this._get_link_target(e),i=this._get_link_source(e);if(!i||!a)return n;if(t.isChildOf(i.id,a.id)&&t._isProject(a)||t.isChildOf(a.id,i.id)&&t._isProject(i))return n;for(var r=this._getImplicitLinks(e,i,function(t){return 0}),s=t.config.auto_scheduling_move_projects,o=this._isProject(a)?this.getSubtaskDates(a.id):{start_date:a.start_date,end_date:a.end_date},u=this._getImplicitLinks(e,a,function(e){return s?e.$target.length||t.getState().drag_id==e.id?0:t.calculateDuration({
start_date:o.start_date,end_date:e.start_date,task:i}):0}),c=0;c<r.length;c++)for(var l=r[c],d=0;d<u.length;d++){var g=u[d],h=1*l.lag+1*g.lag,_={id:e.id,type:e.type,source:l.task,target:g.task,lag:(1*e.lag||0)+h};n.push(t._convertToFinishToStartLink(g.task,_,i,a))}return n},t._getImplicitLinks=function(t,e,n){var a=[];return this._isProject(e)?this.eachTask(function(t){this._isProject(t)||a.push({task:t.id,lag:n(t)})},e.id):a.push({task:e.id,lag:0}),a},t._getDirectDependencies=function(t,e){for(var n=[],a=[],i=e?t.$source:t.$target,r=0;r<i.length;r++){
var s=this.getLink(i[r]);this.isTaskExists(s.source)&&this.isTaskExists(s.target)&&n.push(this.getLink(i[r]))}for(var r=0;r<n.length;r++)a=a.concat(this._formatLink(n[r]));return a},t._getInheritedDependencies=function(t,e){var n=[],a=[];if(this.isTaskExists(t.id)){this._eachParent(function(t){this._isProject(t)&&a.push.apply(a,this._getDirectDependencies(t,e))},t.id,this);for(var i=0;i<a.length;i++){var r=e?a[i].source:a[i].target;r==t.id&&n.push(a[i])}}return n},t._getDirectSuccessors=function(t){
return this._getDirectDependencies(t,!0)},t._getInheritedSuccessors=function(t){return this._getInheritedDependencies(t,!0)},t._getDirectPredecessors=function(t){return this._getDirectDependencies(t,!1)},t._getInheritedPredecessors=function(t){return this._getInheritedDependencies(t,!1)},t._getSuccessors=function(t){return this._getDirectSuccessors(t).concat(this._getInheritedSuccessors(t))},t._getPredecessors=function(t){return this._getDirectPredecessors(t).concat(this._getInheritedPredecessors(t));
},t._convertToFinishToStartLink=function(e,n,a,i){var r={target:e,link:t.config.links.finish_to_start,id:n.id,lag:n.lag||0,source:n.source,preferredStart:null},s=0;switch(n.type){case t.config.links.start_to_start:s=-a.duration;break;case t.config.links.finish_to_finish:s=-i.duration;break;case t.config.links.start_to_finish:s=-a.duration-i.duration;break;default:s=0}return r.lag+=s,r},t.config.auto_scheduling=!1,t.config.auto_scheduling_descendant_links=!1,t.config.auto_scheduling_initial=!0,t.config.auto_scheduling_strict=!1,
t.config.auto_scheduling_move_projects=!0,t._forEach=function(t,e){for(var n=t.slice(),a=0;a<n.length;a++)e(n[a],a)},t._arrayMap=function(t,e){for(var n=t.slice(),a=[],i=0;i<n.length;i++)a.push(e(n[i],i));return a},t._autoSchedulingGraph={getVertices:function(e){var n={};t._forEach(e,function(t){n[t.target]=t.target,n[t.source]=t.source});var a=[];for(var i in n)a.push(n[i]);return a.sort(function(e,n){return t.getGlobalTaskIndex(e)-t.getGlobalTaskIndex(n)})},topologicalSort:function(t){for(var e=this.getVertices(t),n={},a=0;a<e.length;a++)n[e[a]]={
id:e[a],$source:[],$target:[],$incoming:0};for(var a=0;a<t.length;a++){var i=n[t[a].target];i.$target.push(a),i.$incoming=i.$target.length,n[t[a].source].$source.push(a)}for(var r=e.filter(function(t){return!n[t].$incoming}),s=[];r.length;){var o=r.pop();s.push(o);for(var u=n[o],a=0;a<u.$source.length;a++){var c=n[t[u.$source[a]].target];c.$incoming--,c.$incoming||r.push(c.id)}}return s},tarjanStronglyConnectedComponents:function(e,n){function a(e,r){var l=i(e);if(l.index=s,l.lowLink=s,s++,r&&u.push(r),
o.push(l),l.onStack=!0,t._forEach(n,function(t){if(t.source==e){var n=i(t.source),r=i(t.target);void 0===r.index?(a(t.target,t),n.lowLink=Math.min(n.lowLink,r.lowLink)):r.onStack&&(n.lowLink=Math.min(n.lowLink,r.index),u.push(t))}}),l.lowLink==l.index){var d,g={tasks:[],links:[]};do{var h=u.pop();d=o.pop(),d.onStack=!1,g.tasks.push(d.id),h&&g.links.push(h.id)}while(d.id!=l.id);c.push(g)}}function i(t){return r[t]||(r[t]={id:t}),r[t]}var r={},s=0,o=[],u=[],c=[];return t._forEach(e,function(t){var e=i(t);
void 0===e.index&&a(t)}),c}},t._autoSchedulingPath={getKey:function(t){return[t.lag,t.link,t.source,t.target].join("_")},getVirtualRoot:function(){return t.mixin(t.getSubtaskDates(),{id:t.config.root_id,type:t.config.types.project,$source:[],$target:[],$virtual:!0})},filterDuplicates:function(t){for(var e={},n=0;n<t.length;n++){var a=this.getKey(t[n]);e[a]?(t.splice(n,1),n--):e[a]=!0}return t},getLinkedTasks:function(t,e){for(var n=[t],a=[],i={},r=0;r<n.length;r++)a=a.concat(this._getLinkedTasks(n[r],i,e));
return a},_getLinkedTasks:function(e,n,a){var i=void 0===e?t.config.root_id:e,r=n||{},s=t.isTaskExists(i)?t.getTask(i):this.getVirtualRoot(),o=t._getSuccessors(s);a&&o.push.apply(o,t._getPredecessors(s));for(var u=[],c=0;c<o.length;c++)r[this.getKey(o[c])]||(r[this.getKey(o[c])]=!0,u=u.concat(this._getLinkedTasks(o[c].target,r,!0)));for(var l=t.getChildren(s.id),c=0;c<l.length;c++)o=o.concat(this._getLinkedTasks(l[c],r,!0));return this.filterDuplicates(o.concat(u))},findLoops:function(e){var n=[];
t._forEach(e,function(t){t.target==t.source&&n.push([t.target,t.source])});var a=t._autoSchedulingGraph,i=a.getVertices(e),r=a.tarjanStronglyConnectedComponents(i,e);return t._forEach(r,function(t){t.tasks.length>1&&n.push(t)}),n}},t._autoSchedulingDateResolver={isFirstSmaller:function(e,n,a){return e.valueOf()<n.valueOf()&&t._hasDuration(e,n,a)?!0:!1},isSmallerOrDefault:function(t,e,n){return!(t&&!this.isFirstSmaller(t,e,n))},resolveRelationDate:function(e,n,a){for(var i=null,r=null,s=null,o=0;o<n.length;o++){
var u=n[o];e=u.target,s=u.preferredStart;var c=this.getConstraintDate(u,a);this.isSmallerOrDefault(s,c,t.getTask(e))&&this.isSmallerOrDefault(i,c,t.getTask(e))&&(i=c,r=u.id)}return i&&(i=t.getClosestWorkTime({date:i,dir:"future",task:t.getTask(e)})),{link:r,task:e,start_date:i}},getConstraintDate:function(e,n){var a=n(e.source);return a&&e.lag&&1*e.lag==e.lag&&(a=t.calculateEndDate({start_date:a,duration:1*e.lag,task:t.getTask(e.source)})),a}},t._autoSchedulingPlanner={generatePlan:function(e){function n(e){
var n=s[e],a=t.getTask(e);return n&&(n.start_date||n.end_date)?n.end_date?n.end_date:t.calculateEndDate({start_date:n.start_date,duration:a.duration,task:a}):t.getClosestWorkTime({date:a.end_date,dir:"future",task:a})}var a=t._autoSchedulingGraph,i=a.topologicalSort(e),r={},s={};t._arrayMap(i,function(e){var n=t.getTask(e);n.auto_scheduling!==!1&&(r[e]=[],s[e]=null)});for(var o=0;o<e.length;o++)r[e[o].target]&&r[e[o].target].push(e[o]);for(var u=t._autoSchedulingDateResolver,c=[],o=0;o<i.length;o++){
var l=i[o],d=u.resolveRelationDate(l,r[l]||[],n);if(d.start_date&&t.isLinkExists(d.link)){var g=t.getLink(d.link),h=t.getTask(l),_=t.getTask(g.source);if(h.start_date.valueOf()!==d.start_date.valueOf()&&t.callEvent("onBeforeTaskAutoSchedule",[h,d.start_date,g,_])===!1)continue}s[l]=d,d.start_date&&c.push(d)}return c},applyProjectPlan:function(e){for(var n,a,i,r,s=[],o=0;o<e.length;o++)if(i=null,r=null,n=e[o],n.task){a=t.getTask(n.task),n.link&&(i=t.getLink(n.link),r=t.getTask(i.source));var u=null;
n.start_date&&a.start_date.valueOf()!=n.start_date.valueOf()&&(u=n.start_date),u&&(a.start_date=u,a.end_date=t.calculateEndDate(a),s.push(a.id),t.callEvent("onAfterTaskAutoSchedule",[a,u,i,r]))}return s}},t._autoSchedulingPreferredDates=function(e,n){for(var a=0;a<n.length;a++){var i=n[a],r=t.getTask(i.target);t.config.auto_scheduling_strict&&i.target!=e||(i.preferredStart=new Date(r.start_date))}},t._autoSchedule=function(e,n,a){if(t.callEvent("onBeforeAutoSchedule",[e])!==!1){t._autoscheduling_in_progress=!0;
var i=t._autoSchedulingPath,r=[],s=i.findLoops(n);if(s.length)t.callEvent("onAutoScheduleCircularLink",[s]);else{var o=t._autoSchedulingPlanner;t._autoSchedulingPreferredDates(e,n);var u=o.generatePlan(n);r=o.applyProjectPlan(u),a&&a(r)}return t._autoscheduling_in_progress=!1,t.callEvent("onAfterAutoSchedule",[e,r]),r}},t.autoSchedule=function(e,n){n=void 0===n?!0:!!n;var a=t._autoSchedulingPath.getLinkedTasks(e,n);t._autoSchedule(e,a,t._finalizeAutoSchedulingChanges)},t._finalizeAutoSchedulingChanges=function(e){
function n(e){if(!i){var a=e.start_date.valueOf(),r=e.end_date.valueOf();if(t.resetProjectDates(e),e.start_date.valueOf()!=a||e.end_date.valueOf()!=r)return void(i=!0);for(var s=t.getChildren(e.id),o=0;!i&&o<s.length;o++)n(t.getTask(s[o]))}}function a(){for(var n=0;n<e.length;n++)t.updateTask(e[n])}var i=!1;1==e.length?t._eachParent(n,e[0]):e.length&&(i=!0),i?t.batchUpdate(a):a()},t.isCircularLink=function(e){return!!t._getConnectedGroup(e)},t._getConnectedGroup=function(e){var n=t._autoSchedulingPath,a=n.getLinkedTasks();
t.isLinkExists(e.id)||(a=a.concat(t._formatLink(e)));for(var i=n.findLoops(a),r=!1,s=0;s<i.length&&!r;s++)for(var o=i[s].links,u=0;u<o.length;u++)if(o[u]==e.id)return i[s];return null},t.findCycles=function(){var e=t._autoSchedulingPath,n=e.getLinkedTasks();return e.findLoops(n)},t._attachAutoSchedulingHandlers=function(){function e(e,n){for(var a=!1,i=0;i<n.length;i++){var r=t.getLink(n[i].id);(r.type==t.config.links.start_to_start||r.type==t.config.links.start_to_finish)&&(n.splice(i,1),i--,a=!0);
}if(a){for(var s={},i=0;i<n.length;i++)s[n[i].id]=!0;for(var o=t._autoSchedulingPath.getLinkedTasks(e,!0),i=0;i<o.length;i++)s[o[i].id]||n.push(o[i])}}t._autoScheduleAfterLinkChange=function(e,n){t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t.autoSchedule(n.source)},t.attachEvent("onAfterLinkUpdate",t._autoScheduleAfterLinkChange),t.attachEvent("onAfterLinkAdd",t._autoScheduleAfterLinkChange),t.attachEvent("onParse",function(){t.config.auto_scheduling&&t.config.auto_scheduling_initial&&t.autoSchedule();
}),t._preventCircularLink=function(e,n){return t.isCircularLink(n)?(t.callEvent("onCircularLinkError",[n,t._getConnectedGroup(n)]),!1):!0},t._preventDescendantLink=function(e,n){var a=t.getTask(n.source),i=t.getTask(n.target);return!t.config.auto_scheduling_descendant_links&&(t.isChildOf(a.id,i.id)&&t._isProject(i)||t.isChildOf(i.id,a.id)&&t._isProject(a))?!1:!0},t.attachEvent("onBeforeLinkAdd",t._preventCircularLink),t.attachEvent("onBeforeLinkAdd",t._preventDescendantLink),t.attachEvent("onBeforeLinkUpdate",t._preventCircularLink),
t.attachEvent("onBeforeLinkUpdate",t._preventDescendantLink),t._datesNotEqual=function(t,e,n,a){return t.valueOf()>e.valueOf()?this._hasDuration({start_date:e,end_date:t,task:a}):this._hasDuration({start_date:t,end_date:e,task:n})},t._notEqualTaskDates=function(e,n){return this._datesNotEqual(e.start_date,n.start_date,e,n)||(this._datesNotEqual(e.end_date,n.end_date,e,n)||e.duration!=n.duration)&&e.type!=t.config.types.milestone?!0:void 0};var n,a;t.attachEvent("onBeforeTaskDrag",function(e,i,r){
return t.config.auto_scheduling_move_projects&&(n=t._autoSchedulingPath.getLinkedTasks(e,!0),a=e),!0}),t._autoScheduleAfterDND=function(i,r){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){var s=this.getTask(i);t._notEqualTaskDates(r,s)&&(t.config.auto_scheduling_move_projects&&a==i?(t.calculateDuration(r)!=t.calculateDuration(s)&&e(i,n),t._autoSchedule(i,n,t._finalizeAutoSchedulingChanges)):t.autoSchedule(s.id))}return n=null,a=null,!0},t._lightBoxChangesHandler=function(e,n){if(t.config.auto_scheduling&&!this._autoscheduling_in_progress){
var a=this.getTask(e);t._notEqualTaskDates(n,a)&&(t._autoschedule_lightbox_id=e)}return!0},t._lightBoxSaveHandler=function(e,n){return t.config.auto_scheduling&&!this._autoscheduling_in_progress&&t._autoschedule_lightbox_id&&t._autoschedule_lightbox_id==e&&(t._autoschedule_lightbox_id=null,t.autoSchedule(n.id)),!0},t.attachEvent("onBeforeTaskChanged",function(e,n,a){return t._autoScheduleAfterDND(e,a)}),t.attachEvent("onLightboxSave",t._lightBoxChangesHandler),t.attachEvent("onAfterTaskUpdate",t._lightBoxSaveHandler);
},t.attachEvent("onGanttReady",function(){t._attachAutoSchedulingHandlers()})});
//# sourceMappingURL=../sources/ext/dhtmlxgantt_auto_scheduling.js.map